import type { Metadata } from "next";
import { SUPPORT_EMAIL } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Privacy Policy — FinTrack",
  description:
    "How FinTrack collects, uses, and protects your information.",
};

export default function PrivacyPage() {
  return (
    <article className="mx-auto max-w-2xl px-6 py-16 prose-content">
      <h1 className="text-3xl font-semibold tracking-tight">
        Privacy Policy
      </h1>
      <p className="mt-2 muted text-sm">Last updated: March 10, 2026</p>

      <p className="mt-8 leading-relaxed">
        FinTrack ("the App") is a personal finance tracking application
        designed to help users manage income, expenses, and loans. This
        Privacy Policy explains how information is collected, used, and
        protected when using the application.
      </p>
      <p className="mt-4 leading-relaxed">
        By using FinTrack, you agree to the collection and use of
        information in accordance with this Privacy Policy.
      </p>

      <Section title="Information Collection">
        <p>FinTrack collects only the information necessary to provide its core functionality.</p>

        <h3 className="mt-6 font-medium">Account Information</h3>
        <p className="mt-2">
          When creating an account, users authenticate using email or Apple
          Sign-In. Authentication and account management are handled
          through Supabase. The following information may be collected and
          associated with the user's account:
        </p>
        <ul className="mt-2 list-disc pl-6 space-y-1">
          <li>Email address</li>
          <li>Authentication identifier generated by Supabase</li>
          <li>Apple Sign-In identifier (if Apple authentication is used)</li>
        </ul>
        <p className="mt-3">
          This information is linked to the user's identity in order to
          enable secure login, data synchronization across devices, and
          account management.
        </p>

        <h3 className="mt-6 font-medium">Financial Data</h3>
        <p className="mt-2">
          Users may store personal financial information in the app,
          including:
        </p>
        <ul className="mt-2 list-disc pl-6 space-y-1">
          <li>Income records</li>
          <li>Expense records</li>
          <li>Loan records (borrowed or lent amounts)</li>
          <li>Categories and notes related to financial entries</li>
        </ul>
        <p className="mt-3">
          This information is created and managed entirely by the user and
          is stored in the user's secure account database.
        </p>

        <h3 className="mt-6 font-medium">Device Security Data</h3>
        <p className="mt-2">
          FinTrack may use device-level security features such as:
        </p>
        <ul className="mt-2 list-disc pl-6 space-y-1">
          <li>Face ID authentication</li>
          <li>Local PIN codes</li>
        </ul>
        <p className="mt-3">
          These features are processed locally on the user's device and are
          not transmitted to external servers.
        </p>
      </Section>

      <Section title="Data Usage">
        <p>
          The information collected is used strictly for the purpose of
          operating and improving the FinTrack application.
        </p>
        <p className="mt-3">Specifically, the data is used to:</p>
        <ul className="mt-2 list-disc pl-6 space-y-1">
          <li>Authenticate users and manage accounts</li>
          <li>Synchronize financial records across devices using Supabase</li>
          <li>Provide core application features such as income, expense, and loan tracking</li>
          <li>Maintain application security and prevent unauthorized access</li>
          <li>Enable users to access their personal financial records from multiple devices</li>
        </ul>
        <p className="mt-4">
          FinTrack does <strong>not sell, rent, or trade user data</strong>{" "}
          to third parties.
        </p>
        <p className="mt-2">
          User financial data is only accessible to the authenticated user
          associated with the account.
        </p>
      </Section>

      <Section title="Data Security">
        <p>FinTrack takes reasonable measures to protect user information.</p>
        <p className="mt-3">Security measures include:</p>
        <ul className="mt-2 list-disc pl-6 space-y-1">
          <li>Secure authentication provided through Supabase</li>
          <li>Encrypted communication between the application and cloud services</li>
          <li>Local device security using Face ID and optional PIN protection</li>
          <li>Access controls ensuring users can only access their own data</li>
        </ul>
        <p className="mt-3">
          Despite these protections, no method of internet transmission or
          electronic storage is completely secure. Therefore, absolute
          security cannot be guaranteed.
        </p>
      </Section>

      <Section title="User Rights">
        <p>Users retain full control over their data stored in FinTrack.</p>
        <p className="mt-3">Users have the right to:</p>
        <ul className="mt-2 list-disc pl-6 space-y-1">
          <li>Access their stored financial data within the application</li>
          <li>Modify or delete individual financial records at any time</li>
          <li>Delete their account and all associated data directly from the app settings</li>
        </ul>
        <p className="mt-3">
          When an account is deleted, all user data associated with the
          account is permanently removed from the system.
        </p>
      </Section>

      <Section title="Third-Party Services">
        <p>FinTrack relies on the following third-party service:</p>
        <p className="mt-3 font-medium">Supabase</p>
        <p className="mt-2">
          Supabase provides authentication and secure cloud data storage.
          When using the app, certain account identifiers (such as email or
          Apple authentication identifiers) are processed through Supabase
          to enable login and synchronization functionality.
        </p>
        <p className="mt-2">
          Users are encouraged to review Supabase's privacy policies for
          more information on how that service manages data.
        </p>
      </Section>

      <Section title="Children's Privacy">
        <p>
          FinTrack is not directed toward children under the age of 13. The
          app does not knowingly collect personal information from
          children.
        </p>
        <p className="mt-3">
          If it becomes known that personal information from a child under
          13 has been collected without parental consent, appropriate steps
          will be taken to remove that information.
        </p>
      </Section>

      <Section title="Changes to This Privacy Policy">
        <p>
          This Privacy Policy may be updated from time to time. Updates
          will be reflected by revising the "Last Updated" date at the top
          of this document.
        </p>
        <p className="mt-3">
          Continued use of the application after any changes indicates
          acceptance of the updated policy.
        </p>
      </Section>

      <Section title="Contact">
        <p>
          If you have questions regarding this Privacy Policy, you may
          contact us at{" "}
          <a
            className="underline"
            href={`mailto:${SUPPORT_EMAIL}`}
          >
            {SUPPORT_EMAIL}
          </a>
          .
        </p>
      </Section>

      {/* TODO: Legal review before App Store submission. */}
    </article>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <section className="mt-10">
      <h2 className="text-xl font-semibold tracking-tight">{title}</h2>
      <div className="mt-3 leading-relaxed text-[15px]">{children}</div>
    </section>
  );
}
